//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OffSync.Mapping.Mappert.Practises.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OffSync.Mapping.Mappert.Practises.Common.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to either rulesToAdd or rulesToRemove must be non-null and contain elements.
        /// </summary>
        internal static string EitherRulesToAddOrRulesToRemoveMustBeNonNullAndContainElements {
            get {
                return ResourceManager.GetString("EitherRulesToAddOrRulesToRemoveMustBeNonNullAndContainElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid builder parameter at index &apos;{0}&apos;: &apos;{1}&apos; must be assignable from &apos;{2}&apos;.
        /// </summary>
        internal static string InvalidBuilderParameterMustBeAssignable {
            get {
                return ResourceManager.GetString("InvalidBuilderParameterMustBeAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid builder return type: &apos;{0}&apos; must be assignable from &apos;{1}&apos;.
        /// </summary>
        internal static string InvalidBuilderReturnTypeMustBeAssignable {
            get {
                return ResourceManager.GetString("InvalidBuilderReturnTypeMustBeAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid builder return type &apos;{0}&apos;, must implement matching ValueTuple or object[].
        /// </summary>
        internal static string InvalidBuilderReturnTypeMustImplementValueTupleOrObjectArray {
            get {
                return ResourceManager.GetString("InvalidBuilderReturnTypeMustImplementValueTupleOrObjectArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid number of builder parameters: &apos;{0}&apos;, expected &apos;{1}&apos;.
        /// </summary>
        internal static string InvalidNumberOfBuilderParameters {
            get {
                return ResourceManager.GetString("InvalidNumberOfBuilderParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid type &apos;{0}&apos;: must be assignable to IMappingDelegateBuilder.
        /// </summary>
        internal static string InvalidTypeMustBeAssignableToIMappingDelegateBuilder {
            get {
                return ResourceManager.GetString("InvalidTypeMustBeAssignableToIMappingDelegateBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message must be provided.
        /// </summary>
        internal static string MessageMustBeProvided {
            get {
                return ResourceManager.GetString("MessageMustBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no mapping delegate registered.
        /// </summary>
        internal static string NoMappingDelegateRegistered {
            get {
                return ResourceManager.GetString("NoMappingDelegateRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetProperties must contain at least one element.
        /// </summary>
        internal static string TargetPropertiesMustContainAtLeastOneElement {
            get {
                return ResourceManager.GetString("TargetPropertiesMustContainAtLeastOneElement", resourceCulture);
            }
        }
    }
}
