parameters:
  projectName: ''

steps:
- task: DotNetCoreCLI@2
  displayName: 'Pack ${{ parameters.projectName }}'
  inputs:
    command: pack
    arguments: '--configuration Release'
    projects: src/${{ parameters.projectName }}/${{ parameters.projectName }}.csproj
    nobuild: true
