//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OffSync.Mapping.Mappert.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OffSync.Mapping.Mappert.Common.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddMappingRule only allowed before rules have been checked.
        /// </summary>
        internal static string AddMappingRuleOnlyAllowedBeforeRulesHaveBeenChecked {
            get {
                return ResourceManager.GetString("AddMappingRuleOnlyAllowedBeforeRulesHaveBeenChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto-mapper not possible for multi-property mapping rule.
        /// </summary>
        internal static string AutoMapperNotPossibleForMultiPropertyMappingRule {
            get {
                return ResourceManager.GetString("AutoMapperNotPossibleForMultiPropertyMappingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto-mapper not possible for target properties-only mapping rule.
        /// </summary>
        internal static string AutoMapperNotPossibleForTargetPropertiesOnlyMappingRule {
            get {
                return ResourceManager.GetString("AutoMapperNotPossibleForTargetPropertiesOnlyMappingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to builder required for multi-property mapping rule.
        /// </summary>
        internal static string BuilderRequiredForMultiPropertyMappingRule {
            get {
                return ResourceManager.GetString("BuilderRequiredForMultiPropertyMappingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to builder required for target properties-only mapping rule.
        /// </summary>
        internal static string BuilderRequiredForTargetPropertiesOnlyMappingRule {
            get {
                return ResourceManager.GetString("BuilderRequiredForTargetPropertiesOnlyMappingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot create auto-mapper: target type &apos;{0}&apos; does not have a parameterless constructor.
        /// </summary>
        internal static string CannotCreateAutoMapperTargetTypeDoesNotHaveParameterlessConstructor {
            get {
                return ResourceManager.GetString("CannotCreateAutoMapperTargetTypeDoesNotHaveParameterlessConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate mapping found for target properties: &apos;{0}&apos;.
        /// </summary>
        internal static string DuplicateMappingFoundForTargetProperties {
            get {
                return ResourceManager.GetString("DuplicateMappingFoundForTargetProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exactly one source property must be mapped for an items mapping, found: &apos;{0}&apos;.
        /// </summary>
        internal static string ExactlyOneSourcePropertyMustBeMappedForItemsMapping {
            get {
                return ResourceManager.GetString("ExactlyOneSourcePropertyMustBeMappedForItemsMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exactly one target property must be mapped for an items mapping, found: &apos;{0}&apos;.
        /// </summary>
        internal static string ExactlyOneTargetPropertyMustBeMappedForItemsMappingFound {
            get {
                return ResourceManager.GetString("ExactlyOneTargetPropertyMustBeMappedForItemsMappingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expression body must access a property.
        /// </summary>
        internal static string ExpressionBodyMustAccessProperty {
            get {
                return ResourceManager.GetString("ExpressionBodyMustAccessProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expression body must by of type MemberExpression.
        /// </summary>
        internal static string ExpressionBodyMustByOfTypeMemberExpression {
            get {
                return ResourceManager.GetString("ExpressionBodyMustByOfTypeMemberExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid builder type: {0}.
        /// </summary>
        internal static string InvalidBuilderType {
            get {
                return ResourceManager.GetString("InvalidBuilderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid type: must implement IMapper&lt;,&gt;.
        /// </summary>
        internal static string InvalidTypeMustImplementIMapper {
            get {
                return ResourceManager.GetString("InvalidTypeMustImplementIMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid type: must implement IMapper&lt;,&gt; exactly once.
        /// </summary>
        internal static string InvalidTypeMustImplementIMapperExactlyOnce {
            get {
                return ResourceManager.GetString("InvalidTypeMustImplementIMapperExactlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no mapping found for source properties: &apos;{0}&apos;.
        /// </summary>
        internal static string NoMappingFoundForSourceProperties {
            get {
                return ResourceManager.GetString("NoMappingFoundForSourceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no mapping found for target properties: &apos;{0}&apos;.
        /// </summary>
        internal static string NoMappingFoundForTargetProperties {
            get {
                return ResourceManager.GetString("NoMappingFoundForTargetProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to create auto-mapper.
        /// </summary>
        internal static string UnableToCreateAutoMapper {
            get {
                return ResourceManager.GetString("UnableToCreateAutoMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to create auto-mapping for property &apos;{0}&apos;.
        /// </summary>
        internal static string UnableToCreateAutoMappingForProperty {
            get {
                return ResourceManager.GetString("UnableToCreateAutoMappingForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to determine source items type for property: &apos;{0}&apos;.
        /// </summary>
        internal static string UnableToDetermineSourceItemsType {
            get {
                return ResourceManager.GetString("UnableToDetermineSourceItemsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to determine target items type for property: &apos;{0}&apos;.
        /// </summary>
        internal static string UnableToDetermineTargetItemsType {
            get {
                return ResourceManager.GetString("UnableToDetermineTargetItemsType", resourceCulture);
            }
        }
    }
}
